#!/usr/bin/env php
<?php

// Check PHP version.
if (version_compare(PHP_VERSION, '8.1', '<')) {
    exit(sprintf('Your PHP version must be 8.1 or higher to run CodeIgniter. Current version: %s', PHP_VERSION));
}

define('COMPOSER_PATH', __DIR__ . '/vendor/autoload.php');

// Path to the front controller (paths acceptable to require_once)
define('FCPATH', __DIR__ . '/public/');

// Ensure the current directory is pointing to the front controller's directory
chdir(__DIR__);

/*
 *---------------------------------------------------------------
 * BOOTSTRAP THE APPLICATION
 *---------------------------------------------------------------
 * This process sets up the path constants, loads and registers
 * our autoloader, along with the framework constants.
 */

// Load our paths config file
require __DIR__ . '/app/Config/Paths.php';

$paths = new Config\Paths();

// Location of the framework bootstrap file.
require $paths->systemDirectory . '/Boot.php';

// Launch the command!
CodeIgniter\Boot::bootSpark($paths);
