-- ==========================================
-- SCHEMA DATABASE: SIAKANUDA
-- Sistem Informasi SMK NU Darussalam
-- Jalankan skrip SQL ini di SQL Editor Supabase Anda.
-- ==========================================

-- -------------------------------------------------------------
-- TAHAP 1: FONDASI DASAR (SISTEM UTAMA & WHATASPP AUTH SESSION)
-- -------------------------------------------------------------

-- 1. Tabel untuk menyimpan sesi login WhatsApp (Baileys) agar tahan restart server
CREATE TABLE IF NOT EXISTS whatsapp_sessions (
    id TEXT PRIMARY KEY,               -- e.g., 'creds' atau nama file key dari Baileys
    data JSONB NOT NULL,               -- Berisi data kredensial/key dalam format JSON
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Mengaktifkan Row Level Security (RLS) untuk keamanan tambahan
ALTER TABLE whatsapp_sessions ENABLE ROW LEVEL SECURITY;

-- Membuat kebijakan agar hanya server backend (service role) yang bisa mengelola sesi WA
CREATE POLICY "Enable read/write for service role only" ON whatsapp_sessions
    FOR ALL USING (true) WITH CHECK (true);


-- 2. Tabel Whitelist Kontak Internal Sekolah (Kontak Terdaftar)
CREATE TABLE IF NOT EXISTS contacts (
    phone TEXT PRIMARY KEY,            -- Format nomor: '628123456789' (tanpa tanda +)
    name TEXT NOT NULL,                -- Nama Guru / Staf / Siswa Ketua Kelompok
    role TEXT NOT NULL,                -- Peran: 'admin', 'guru_bk', 'guru_pkl', 'siswa_pkl', 'alumni', 'wali_murid'
    class_info TEXT,                   -- Keterangan kelas (misal: '11 TKJ', '10 RPL') jika berupa siswa/wali murid
    active BOOLEAN DEFAULT TRUE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

ALTER TABLE contacts ENABLE ROW LEVEL SECURITY;

-- Kebijakan akses publik (hanya baca data contact tertentu jika diperlukan, atau batasi)
CREATE POLICY "Enable read for authenticated users" ON contacts
    FOR SELECT USING (true);


-- 3. Tabel Informasi Teks Statis (BKK Alumni, Info SPP, PPDB, dll.)
CREATE TABLE IF NOT EXISTS school_info (
    key TEXT PRIMARY KEY,              -- Kata kunci pencarian (e.g., 'ppdb', 'bkk', 'spp')
    label TEXT NOT NULL,               -- Judul informasi (e.g., 'Informasi PPDB 2026/2027')
    content_text TEXT NOT NULL,        -- Isi teks balasan panjang yang dikirim ke bot
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

ALTER TABLE school_info ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read access to school_info" ON school_info
    FOR SELECT USING (true);


-- -------------------------------------------------------------
-- TAHAP 2: MODUL BIMBINGAN KONSELING (APLIKASI BK)
-- -------------------------------------------------------------

-- 4. Tabel Absensi Siswa (BK)
CREATE TABLE IF NOT EXISTS bk_attendance (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_name TEXT NOT NULL,
    class_name TEXT NOT NULL,          -- e.g., '10 RPL'
    status TEXT NOT NULL,              -- e.g., 'alpha', 'sakit', 'izin', 'membolos'
    date DATE DEFAULT CURRENT_DATE NOT NULL,
    note TEXT,                         -- Catatan tambahan/keterangan surat
    created_by TEXT,                   -- Nomor WA guru yang menginput
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

ALTER TABLE bk_attendance ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable read for all contacts" ON bk_attendance FOR SELECT USING (true);


-- 5. Tabel Poin Pelanggaran Siswa (BK)
CREATE TABLE IF NOT EXISTS bk_violations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_name TEXT NOT NULL,
    class_name TEXT NOT NULL,
    category TEXT NOT NULL,            -- e.g., 'seragam', 'terlambat', 'rambut'
    points INT DEFAULT 5 NOT NULL,     -- Jumlah poin pelanggaran
    description TEXT,                  -- Kronologi kejadian
    photo_url TEXT,                    -- Tautan gambar bukti di Google Drive
    date DATE DEFAULT CURRENT_DATE NOT NULL,
    created_by TEXT,                   -- Nomor WA guru yang menginput
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

ALTER TABLE bk_violations ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable read for all violations" ON bk_violations FOR SELECT USING (true);


-- 6. Tabel Konseling/Kasus & Tindak Lanjut
CREATE TABLE IF NOT EXISTS bk_counseling (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_name TEXT NOT NULL,
    class_name TEXT NOT NULL,
    type TEXT NOT NULL,                -- e.g., 'counseling' (bimbingan), 'home_visit' (kunjungan rumah)
    content TEXT NOT NULL,             -- Detail hasil konseling/tindak lanjut
    photo_url TEXT,                    -- Foto dokumen pendukung/kunjungan di Google Drive
    date DATE DEFAULT CURRENT_DATE NOT NULL,
    counselor TEXT NOT NULL,           -- Nama guru BK pencatat
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

ALTER TABLE bk_counseling ENABLE ROW LEVEL SECURITY;


-- -------------------------------------------------------------
-- TAHAP 3: MODUL PRAKTIK KERJA LAPANGAN (APLIKASI PKL)
-- -------------------------------------------------------------

-- 7. Tabel Jurnal Harian & Kehadiran PKL Siswa
CREATE TABLE IF NOT EXISTS pkl_journals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_phone TEXT NOT NULL,       -- Nomor WA ketua kelompok / siswa yang melapor
    student_name TEXT NOT NULL,        -- Nama pelapor
    class_name TEXT NOT NULL,          -- Jurusan/Kelas, e.g., '12 TKJ'
    company_name TEXT NOT NULL,        -- Nama DUDI / Tempat Magang
    date DATE DEFAULT CURRENT_DATE NOT NULL,
    journal_text TEXT NOT NULL,        -- Isi jurnal kegiatan hari ini
    photo_url TEXT,                    -- Foto bukti di Google Drive
    status TEXT DEFAULT 'hadir' NOT NULL, -- e.g., 'hadir', 'sakit', 'izin'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

ALTER TABLE pkl_journals ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable read access for pkl journals" ON pkl_journals FOR SELECT USING (true);
