-- =====================================================================
-- MIGRATION SCHEMA: SIAKANUDA v2.0.0 (Supabase Cloud PostgreSQL)
-- Jalankan kode SQL ini di Dashboard Supabase -> SQL Editor -> New Query
-- =====================================================================

-- 1. Tabel schedules (Jadwal Pelajaran)
CREATE TABLE IF NOT EXISTS schedules (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    day VARCHAR(50) NOT NULL,
    class_name VARCHAR(100) NOT NULL,
    subject VARCHAR(200) NOT NULL,
    teacher_phone VARCHAR(50) NOT NULL,
    start_time TIME,
    end_time TIME,
    created_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE schedules ENABLE ROW LEVEL SECURITY;
CREATE POLICY "read_all_schedules" ON schedules FOR SELECT USING (true);
CREATE POLICY "write_service_schedules" ON schedules FOR ALL USING (true) WITH CHECK (true);

-- 2. Tabel feedbacks (Kotak Suara / Aspirasi)
CREATE TABLE IF NOT EXISTS feedbacks (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    date TIMESTAMPTZ DEFAULT NOW(),
    sender_name VARCHAR(255) NOT NULL,
    class_name VARCHAR(100) NOT NULL,
    message TEXT NOT NULL,
    is_public BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE feedbacks ENABLE ROW LEVEL SECURITY;
CREATE POLICY "read_all_feedbacks" ON feedbacks FOR SELECT USING (true);
CREATE POLICY "write_service_feedbacks" ON feedbacks FOR ALL USING (true) WITH CHECK (true);

-- 3. Tabel kelompok_pkl (Pemetaan Kelompok PKL)
CREATE TABLE IF NOT EXISTS kelompok_pkl (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tempat_pkl TEXT NOT NULL,
    ketua_phone TEXT NOT NULL,
    anggota TEXT NOT NULL,
    pembimbing_phone TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);
ALTER TABLE kelompok_pkl ENABLE ROW LEVEL SECURITY;
CREATE POLICY "read_all_kelompok_pkl" ON kelompok_pkl FOR SELECT USING (true);
CREATE POLICY "write_service_kelompok_pkl" ON kelompok_pkl FOR ALL USING (true) WITH CHECK (true);

-- 4. Tabel attendance_pkl (Presensi PKL Harian)
CREATE TABLE IF NOT EXISTS attendance_pkl (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date DATE NOT NULL DEFAULT CURRENT_DATE,
    tempat_pkl TEXT NOT NULL,
    ketua_phone TEXT NOT NULL,
    status_libur BOOLEAN DEFAULT FALSE,
    attendance_data JSONB,
    photo_url TEXT,
    jurnal_kegiatan TEXT,
    is_takeover BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(date, ketua_phone)
);
ALTER TABLE attendance_pkl ENABLE ROW LEVEL SECURITY;
CREATE POLICY "read_all_attendance_pkl" ON attendance_pkl FOR SELECT USING (true);
CREATE POLICY "write_service_attendance_pkl" ON attendance_pkl FOR ALL USING (true) WITH CHECK (true);

-- 5. Tabel attendance_kelas (Presensi Kelas KBM Harian)
CREATE TABLE IF NOT EXISTS attendance_kelas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date DATE NOT NULL DEFAULT CURRENT_DATE,
    class_name TEXT NOT NULL,
    teacher_phone TEXT NOT NULL,
    attendance_data JSONB,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(date, class_name)
);
ALTER TABLE attendance_kelas ENABLE ROW LEVEL SECURITY;
CREATE POLICY "read_all_attendance_kelas" ON attendance_kelas FOR SELECT USING (true);
CREATE POLICY "write_service_attendance_kelas" ON attendance_kelas FOR ALL USING (true) WITH CHECK (true);

-- 6. Indexing untuk Performa
CREATE INDEX IF NOT EXISTS idx_schedules_class_day ON schedules(class_name, day);
CREATE INDEX IF NOT EXISTS idx_schedules_teacher_day ON schedules(teacher_phone, day);
CREATE INDEX IF NOT EXISTS idx_attendance_pkl_date ON attendance_pkl(date);
CREATE INDEX IF NOT EXISTS idx_attendance_kelas_date ON attendance_kelas(date);
CREATE INDEX IF NOT EXISTS idx_kelompok_pkl_ketua ON kelompok_pkl(ketua_phone);
